// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// protoc-gen-go v1.36.8
// protoc        v6.30.2
// source: senzor_podatak.proto

package senzorPodaci

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SenzorPodatak struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Vreme           *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=vreme,proto3" json:"vreme,omitempty"`
	Temperatura     float32                `protobuf:"fixed32,3,opt,name=temperatura,proto3" json:"temperatura,omitempty"`
	VlaznostVazduha float32                `protobuf:"fixed32,4,opt,name=vlaznostVazduha,proto3" json:"vlaznostVazduha,omitempty"`
	Pm2_5           float32                `protobuf:"fixed32,5,opt,name=pm2_5,json=pm25,proto3" json:"pm2_5,omitempty"`
	Pm10            float32                `protobuf:"fixed32,6,opt,name=pm10,proto3" json:"pm10,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *SenzorPodatak) Reset() {
	*x = SenzorPodatak{}
	mi := &file_senzor_podatak_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SenzorPodatak) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SenzorPodatak) ProtoMessage() {}

func (x *SenzorPodatak) ProtoReflect() protoreflect.Message {
	mi := &file_senzor_podatak_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SenzorPodatak.ProtoReflect.Descriptor instead.
func (*SenzorPodatak) Descriptor() ([]byte, []int) {
	return file_senzor_podatak_proto_rawDescGZIP(), []int{0}
}

func (x *SenzorPodatak) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *SenzorPodatak) GetVreme() *timestamppb.Timestamp {
	if x != nil {
		return x.Vreme
	}
	return nil
}

func (x *SenzorPodatak) GetTemperatura() float32 {
	if x != nil {
		return x.Temperatura
	}
	return 0
}

func (x *SenzorPodatak) GetVlaznostVazduha() float32 {
	if x != nil {
		return x.VlaznostVazduha
	}
	return 0
}

func (x *SenzorPodatak) GetPm2_5() float32 {
	if x != nil {
		return x.Pm2_5
	}
	return 0
}

func (x *SenzorPodatak) GetPm10() float32 {
	if x != nil {
		return x.Pm10
	}
	return 0
}

type VremenskiPeriod struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pocetak       *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=pocetak,proto3" json:"pocetak,omitempty"`
	Kraj          *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=kraj,proto3" json:"kraj,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VremenskiPeriod) Reset() {
	*x = VremenskiPeriod{}
	mi := &file_senzor_podatak_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VremenskiPeriod) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VremenskiPeriod) ProtoMessage() {}

func (x *VremenskiPeriod) ProtoReflect() protoreflect.Message {
	mi := &file_senzor_podatak_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VremenskiPeriod.ProtoReflect.Descriptor instead.
func (*VremenskiPeriod) Descriptor() ([]byte, []int) {
	return file_senzor_podatak_proto_rawDescGZIP(), []int{1}
}

func (x *VremenskiPeriod) GetPocetak() *timestamppb.Timestamp {
	if x != nil {
		return x.Pocetak
	}
	return nil
}

func (x *VremenskiPeriod) GetKraj() *timestamppb.Timestamp {
	if x != nil {
		return x.Kraj
	}
	return nil
}

var File_senzor_podatak_proto protoreflect.FileDescriptor

const file_senzor_podatak_proto_rawDesc = "" +
	"\n" +
	"\x14senzor_podatak.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1egoogle/protobuf/wrappers.proto\x1a\x1bgoogle/protobuf/empty.proto\"\xc6\x01\n" +
	"\rSenzorPodatak\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x120\n" +
	"\x05vreme\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\x05vreme\x12 \n" +
	"\vtemperatura\x18\x03 \x01(\x02R\vtemperatura\x12(\n" +
	"\x0fvlaznostVazduha\x18\x04 \x01(\x02R\x0fvlaznostVazduha\x12\x13\n" +
	"\x05pm2_5\x18\x05 \x01(\x02R\x04pm25\x12\x12\n" +
	"\x04pm10\x18\x06 \x01(\x02R\x04pm10\"w\n" +
	"\x0fVremenskiPeriod\x124\n" +
	"\apocetak\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\apocetak\x12.\n" +
	"\x04kraj\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\x04kraj2\xad\x03\n" +
	"\fSenzorPodaci\x12C\n" +
	"\x12VratiSenzorPodatak\x12\x1b.google.protobuf.Int32Value\x1a\x0e.SenzorPodatak\"\x00\x12=\n" +
	"\x0fSviSenzorPodaci\x12\x16.google.protobuf.Empty\x1a\x0e.SenzorPodatak\"\x000\x01\x12B\n" +
	"\x12DodajSenzorPodatak\x12\x0e.SenzorPodatak\x1a\x1a.google.protobuf.BoolValue\"\x00\x12C\n" +
	"\x13IzmeniSenzorPodatak\x12\x0e.SenzorPodatak\x1a\x1a.google.protobuf.BoolValue\"\x00\x12Q\n" +
	"\x14IzbrisiSenzorPodatak\x12\x1b.google.protobuf.Int32Value\x1a\x1a.google.protobuf.BoolValue\"\x00\x12=\n" +
	"\x15SviSenzorPodaciPeriod\x12\x10.VremenskiPeriod\x1a\x0e.SenzorPodatak\"\x000\x01B\x10Z\x0e./senzorPodacib\x06proto3"

var (
	file_senzor_podatak_proto_rawDescOnce sync.Once
	file_senzor_podatak_proto_rawDescData []byte
)

func file_senzor_podatak_proto_rawDescGZIP() []byte {
	file_senzor_podatak_proto_rawDescOnce.Do(func() {
		file_senzor_podatak_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_senzor_podatak_proto_rawDesc), len(file_senzor_podatak_proto_rawDesc)))
	})
	return file_senzor_podatak_proto_rawDescData
}

var file_senzor_podatak_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_senzor_podatak_proto_goTypes = []any{
	(*SenzorPodatak)(nil),         // 0: SenzorPodatak
	(*VremenskiPeriod)(nil),       // 1: VremenskiPeriod
	(*timestamppb.Timestamp)(nil), // 2: google.protobuf.Timestamp
	(*wrapperspb.Int32Value)(nil), // 3: google.protobuf.Int32Value
	(*emptypb.Empty)(nil),         // 4: google.protobuf.Empty
	(*wrapperspb.BoolValue)(nil),  // 5: google.protobuf.BoolValue
}
var file_senzor_podatak_proto_depIdxs = []int32{
	2, // 0: SenzorPodatak.vreme:type_name -> google.protobuf.Timestamp
	2, // 1: VremenskiPeriod.pocetak:type_name -> google.protobuf.Timestamp
	2, // 2: VremenskiPeriod.kraj:type_name -> google.protobuf.Timestamp
	3, // 3: SenzorPodaci.VratiSenzorPodatak:input_type -> google.protobuf.Int32Value
	4, // 4: SenzorPodaci.SviSenzorPodaci:input_type -> google.protobuf.Empty
	0, // 5: SenzorPodaci.DodajSenzorPodatak:input_type -> SenzorPodatak
	0, // 6: SenzorPodaci.IzmeniSenzorPodatak:input_type -> SenzorPodatak
	3, // 7: SenzorPodaci.IzbrisiSenzorPodatak:input_type -> google.protobuf.Int32Value
	1, // 8: SenzorPodaci.SviSenzorPodaciPeriod:input_type -> VremenskiPeriod
	0, // 9: SenzorPodaci.VratiSenzorPodatak:output_type -> SenzorPodatak
	0, // 10: SenzorPodaci.SviSenzorPodaci:output_type -> SenzorPodatak
	5, // 11: SenzorPodaci.DodajSenzorPodatak:output_type -> google.protobuf.BoolValue
	5, // 12: SenzorPodaci.IzmeniSenzorPodatak:output_type -> google.protobuf.BoolValue
	5, // 13: SenzorPodaci.IzbrisiSenzorPodatak:output_type -> google.protobuf.BoolValue
	0, // 14: SenzorPodaci.SviSenzorPodaciPeriod:output_type -> SenzorPodatak
	9, // [9:15] is the sub-list for method output_type
	3, // [3:9] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_senzor_podatak_proto_init() }
func file_senzor_podatak_proto_init() {
	if File_senzor_podatak_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_senzor_podatak_proto_rawDesc), len(file_senzor_podatak_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_senzor_podatak_proto_goTypes,
		DependencyIndexes: file_senzor_podatak_proto_depIdxs,
		MessageInfos:      file_senzor_podatak_proto_msgTypes,
	}.Build()
	File_senzor_podatak_proto = out.File
	file_senzor_podatak_proto_goTypes = nil
	file_senzor_podatak_proto_depIdxs = nil
}
